### ISSUE TITLE
cpu temp

### ISSUE THREAD

**Issue by BrunoTeixeira1996** [gokrazy/stat#3]
Just wondering if its possible to get cpu temp using the webstat in gokrazy and in stat from terminal?

Thanks

**Comment by BrunoTeixeira1996** [comment]
Using the following command I got this temp, not sure if its 100% accurate

```
/tmp/breakglass2122018228 # cat /sys/class/thermal/thermal_zone0/temp 
53069
```

**Comment by stapelberg** [comment]
That’s not currently possible, but you can send a PR for it if you want.

Look at the code in `internal/*` to see how stat modules are implemented and add one that reads thermal_zone0/temp. 

I think we wouldn’t necessarily want to display the temperature in the default configuration as space is rather limited depending on the screen resolution. But we can make the temperature show up with a flag.

**Comment by BrunoTeixeira1996** [comment]
I plan working on this in a few days!
Ill get back to you with updates

**Comment by BrunoTeixeira1996** [comment]
So the pull request was created https://github.com/gokrazy/stat/pull/4
